server:
  port: 4000

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring2go_upms?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

# mybatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.spring2go
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/**/*.xml

# swagger配置
swagger:
  enabled: true
  title: UPMS 系统模块接口文档